name: Assign Reviewers to PRs

on:
  pull_request:
    branches:
      - 'feature/*'

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Assign reviewer from sca-qe team
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviewers = ['reviewer1', 'reviewer2', 'reviewer3']; // Add your sca-qe team reviewers here
            const team_slug = 'sca-qe'; // Replace with your actual team slug

            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;

            const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');

            // Assign a random reviewer from the list
            const reviewer = reviewers[Math.floor(Math.random() * reviewers.length)];

            // Add the chosen reviewer to the PR
            await octokit.rest.pulls.createReviewRequest({
              owner,
              repo,
              pull_number: pr_number,
              reviewers: [reviewer],
              team_reviewers: [team_slug]
            });
